name: 'Dispense Token'
description: 'Requests a new token from the token dispenser'
inputs:
  hostname:
    description: 'The token dispenser hostname to use'
    required: true
  repo:
    description: 'The repository to request access to'
    required: true
  permissions:
    description: 'The permissions to request'
    required: true
outputs:
  token:
    description: 'The authorized GitHub token'
runs:
  using: 'node16'
  main: 'dist/index.js'
